// apps/myapp/src/app/app.component.ts
import '@workshop/ui-web-card';

import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { ICard } from '@workshop/types';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

@Component({
	selector: 'workshop-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss'],
})
export class AppComponent {
	public title = 'Workshop';
	public cards$: Observable<ICard[]>;

	constructor(private http: HttpClient) {
		this.cards$ = this.http.get('http://localhost:4200/api/cards').pipe(map((res: ICard[]) => res));
	}
}

<div class="container">
	<div class="header">
		<h1>{{ title }}</h1>
		<img src="https://nx.dev/assets/images/nx-logo.svg" />
	</div>

	<card-wrapper>
		<card-content *ngFor="let card of cards$ | async">
			<card-title>{{ card.title }}</card-title>
			<card-description>{{ card.description }}</card-description>
			<card-box [attr.color]="card.boxColor"></card-box>
		</card-content>
	</card-wrapper>
</div>

// apps/reactapp/src/app/app.tsx
import './app.scss';
import '@workshop/ui-web-card';

import { ICard } from '@workshop/types';
import React, { useEffect, useState } from 'react';

export const App = () => {
	const [apiResponse, setApiResponse] = useState<ICard[]>([]);
	useEffect(() => {
		fetch('/api/cards')
			.then((r) => {
				return r.json();
			})
			.then(setApiResponse);
	}, []);
	/*
	 * Replace the elements below with your own.
	 *
	 * Note: The corresponding styles are in the ./app.scss file.
	 */
	return (
		<div className="app">
			<main>
				<div className="container">
					<div className="header">
						<h1>App</h1>
						<img src="https://nx.dev/assets/images/nx-logo.svg" />
					</div>
					<card-wrapper>
						{apiResponse.map((card) => (
							<card-content>
								<card-title>{card.title}</card-title>
								<card-description>{card.description}</card-description>
								<card-box color={card.boxColor}></card-box>
							</card-content>
						))}
					</card-wrapper>
				</div>
			</main>
		</div>
	);
};

export default App;
